# Generated by Django 2.0.3 on 2018-03-19 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelist',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
