# Generated by Django 2.0.4 on 2018-05-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgandrate',
            name='ecgdata',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='ecgandratedetail',
            name='ecgdata',
            field=models.CharField(max_length=3000),
        ),
    ]
