# Generated by Django 2.0.4 on 2018-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_auto_20180510_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgandrate',
            name='ecgdata',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ecgandratedetail',
            name='ecgdata',
            field=models.TextField(),
        ),
    ]
