# Generated by Django 2.0.3 on 2018-03-20 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0003_auto_20180319_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tem',
            new_name='Temp',
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='user',
            field=models.ManyToManyField(related_name='devicelist', to=settings.AUTH_USER_MODEL),
        ),
    ]
