# Generated by Django 2.0.3 on 2018-03-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_auto_20180320_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyr',
            name='accx',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='gyr',
            name='accy',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='gyr',
            name='accz',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='gyr',
            name='anglex',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='gyr',
            name='angley',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='gyr',
            name='anglez',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='gyr',
            name='omegax',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='gyr',
            name='omegay',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='gyr',
            name='omegaz',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='temp',
            name='ta',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='temp',
            name='to',
            field=models.CharField(max_length=10),
        ),
    ]
