# Generated by Django 2.0.3 on 2018-03-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0005_auto_20180320_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='n_s',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='map',
            name='w_e',
            field=models.CharField(max_length=8),
        ),
    ]
