# Generated by Django 2.0.3 on 2018-03-22 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0006_auto_20180321_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyr',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyr', to='watcher.DeviceList'),
        ),
        migrations.AlterField(
            model_name='map',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='watcher.DeviceList'),
        ),
    ]
