# Generated by Django 2.0.3 on 2018-03-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0007_auto_20180322_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta', models.CharField(max_length=10)),
                ('to', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temper_detail', to='watcher.DeviceList')),
            ],
        ),
    ]
