# Generated by Django 2.0.3 on 2018-03-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0008_tempdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdetail',
            name='device',
        ),
        migrations.DeleteModel(
            name='TempDetail',
        ),
    ]
