# Generated by Django 2.0.3 on 2018-03-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0010_tempdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='tempdetail',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='temper_detail', serialize=False, to='watcher.DeviceList'),
        ),
    ]
