# Generated by Django 2.0.3 on 2018-03-28 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0011_auto_20180328_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='GyrDetail',
            fields=[
                ('accx', models.CharField(max_length=25)),
                ('accy', models.CharField(max_length=25)),
                ('accz', models.CharField(max_length=25)),
                ('omegax', models.CharField(max_length=25)),
                ('omegay', models.CharField(max_length=25)),
                ('omegaz', models.CharField(max_length=25)),
                ('anglex', models.CharField(max_length=25)),
                ('angley', models.CharField(max_length=25)),
                ('anglez', models.CharField(max_length=25)),
                ('fall', models.BooleanField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gyr_detail', serialize=False, to='watcher.DeviceList')),
            ],
        ),
        migrations.CreateModel(
            name='MapDetail',
            fields=[
                ('n_s', models.CharField(max_length=8)),
                ('w_e', models.CharField(max_length=8)),
                ('time', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='map_detail', serialize=False, to='watcher.DeviceList')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gyr',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='temp',
            options={'ordering': ['-id']},
        ),
    ]
