# Generated by Django 2.0.3 on 2018-04-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0012_auto_20180328_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp',
            options={'ordering': ['id']},
        ),
    ]
