# Generated by Django 2.0.3 on 2018-04-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0014_auto_20180411_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyr',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gyrdetail',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mapdetail',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='temp',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tempdetail',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
