# Generated by Django 2.0.3 on 2018-04-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0015_auto_20180411_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyr',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gyr',
            name='timestamp',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='gyrdetail',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gyrdetail',
            name='timestamp',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='timestamp',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='mapdetail',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mapdetail',
            name='timestamp',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='temp',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='temp',
            name='timestamp',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tempdetail',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tempdetail',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
