# Generated by Django 2.0.3 on 2018-04-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0018_auto_20180413_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='latitude',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='map',
            name='longitude',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mapdetail',
            name='latitude',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mapdetail',
            name='longitude',
            field=models.CharField(max_length=15),
        ),
    ]
