# Generated by Django 2.0.3 on 2018-04-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0019_auto_20180413_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdetail',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
