# Generated by Django 2.0.3 on 2018-04-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0020_auto_20180413_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gyr',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='temp',
            options={'ordering': ['-id']},
        ),
    ]
