# Generated by Django 2.0.4 on 2018-05-10 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0022_auto_20180413_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcgAndRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecgdata', models.Field()),
                ('rate', models.IntegerField()),
                ('timestamp', models.TimeField()),
                ('time', models.TimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EcgAndRateDetail',
            fields=[
                ('ecgdata', models.Field()),
                ('rate', models.IntegerField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ecg_detail', serialize=False, to='watcher.DeviceList')),
                ('timestamp', models.TimeField()),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ecgandrate',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecg', to='watcher.DeviceList'),
        ),
    ]
