# Generated by Django 2.0.4 on 2018-05-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0023_auto_20180510_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecgandrate',
            name='ecgdata',
        ),
        migrations.RemoveField(
            model_name='ecgandratedetail',
            name='ecgdata',
        ),
    ]
